name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Tests
      run: npm test

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
          ${{ secrets.DOCKER_USERNAME }}/nodejs-app:${{ github.sha }}

  deploy:
   runs-on: ubuntu-latest
   needs: build-and-push-docker-image

   steps:
    - name: Add SSH Private Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
        echo "Connected to EC2 instance!"
        sudo docker stop nodejs-app || true
        sudo docker rm nodejs-app || true
        sudo docker container prune -f
        sudo docker images prune -f
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
        sudo docker run -d --name nodejs-app -p 3000:3000 --restart always ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest
        EOF

    - name: Set up Nginx for port forwarding 
      run: |
          sudo tee /etc/nginx/sites-available/default << EOL
          server {
            listen 80;
            server_name _;
  
            location / {
              proxy_pass http://localhost:3000;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto \$scheme;
            }
          }
          EOL
  
          # Restart Nginx to apply the changes
          sudo systemctl restart nginx

    - name: Notify on Success
      if: success()
      run: |
        echo "Deployment Successful!"

    - name: Notify on Failure
      if: failure()
      run: |
        echo "Deployment Failed!"